# 1. Estratégia de geração das tabelas (PostgreSQL via Dev Services)
quarkus.hibernate-orm.generation=drop-and-create

# 2. Configuração do Emissor esperado pelo Token
mp.jwt.verify.issuer=https://shopi.com/issuer

# 3. SEGURANÇA JWT EM MEMÓRIA (Configuração Oficial de Dev Mode)
# Removemos completamente a linha ".key.location" para o Quarkus não buscar arquivos ou URLs.
# Ao definir apenas o algoritmo e o tamanho, o SmallRye gera uma chave RSA válida direto na memória RAM.
smallrye.jwt.sign.key.algorithm=RS256