# Estratégia de geração das tabelas do Hibernate (Recria o esquema a cada boot no container)
quarkus.hibernate-orm.database.generation=drop-and-create

# Ativação da Segurança baseada em Banco de Dados (JPA)
quarkus.security.jpa.enabled=true

# Configuração do Emissor
mp.jwt.verify.issuer=https://shopi.com/issuer

# verificação do Token JWT
smallrye.jwt.sign.key.location=privateKey.pem